# Generated by Django 4.2.2 on 2023-09-11 22:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KlingReply',
            new_name='CommentReply',
        ),
    ]
