# Generated by Django 4.2.4 on 2023-08-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=700)),
            ],
        ),
        migrations.AlterField(
            model_name='kling',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
