# Generated by Django 4.2.4 on 2023-08-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kling',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
