# Generated by Django 4.2.4 on 2023-09-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_klingreply_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kling',
            name='kling_category',
            field=models.CharField(choices=[('1', 'Life and Love'), ('2', 'Travel and Adventure'), ('3', 'Art and Music'), ('4', 'Nature'), ('5', 'Food and Wellness'), ('6', 'Careers'), ('7', 'Science and Technology'), ('8', 'Other')], max_length=22),
        ),
    ]
