# Generated by Django 4.2.2 on 2023-08-07 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cackling_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cackling',
            name='submit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
