# Generated by Django 4.2.2 on 2023-08-31 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_kling_image'),
        ('core', '0002_message_alter_kling_image'),
    ]

    operations = [
    ]
