# Generated by Django 4.2.2 on 2023-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cackling_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cackling',
            name='submit_date',
            field=models.DateTimeField(),
        ),
    ]
