# Generated by Django 3.2.18 on 2023-09-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_kling_kling_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kling',
            name='kling_type',
            field=models.CharField(choices=[('1', 'Hot'), ('2', 'Standart'), ('3', 'Relaxing')], max_length=1),
        ),
    ]
