# Generated by Django 4.2.2 on 2023-08-09 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_cackling_submit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField()),
                ('category', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(max_length=2000)),
                ('kling_type', models.CharField(choices=[('1', 'Hot'), ('2', 'Standard'), ('3', 'Relaxing')], default='2', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cackling',
        ),
    ]
