# Generated by Django 3.2.18 on 2023-09-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230910_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='kling',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
