# Generated by Django 4.2.2 on 2023-08-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_kling_delete_cackling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kling',
            name='submit_date',
        ),
        migrations.AddField(
            model_name='kling',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
