# Generated by Django 4.2.4 on 2023-08-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_kling_submit_date_kling_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kling',
            name='category',
        ),
        migrations.AddField(
            model_name='kling',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Media'),
        ),
        migrations.AddField(
            model_name='kling',
            name='kling_category',
            field=models.CharField(choices=[('Life and Love', 'Life and Love'), ('Travel and Adventure', 'Travel and Adventure'), ('Art and Music', 'Art and Music'), ('Nature', 'Nature'), ('Food and Wellness', 'Food and Wellness'), ('Careers', 'Careers'), ('Science and Technology', 'Science and Technology'), ('Other', 'Other')], default=1, max_length=22),
            preserve_default=False,
        ),
    ]
