# Generated by Django 4.2.4 on 2023-08-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_kling_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kling',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
